// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaAsZ61RXmlbaOd4arcTXuvR85fw33bhY',
    appId: '1:851203059837:web:ede7875fd1e706b6a74114',
    messagingSenderId: '851203059837',
    projectId: 'petlover-c9863',
    authDomain: 'petlover-c9863.firebaseapp.com',
    storageBucket: 'petlover-c9863.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCVWDb0TOdFgbFnkj6fsJn5BMCP-Gq2M',
    appId: '1:851203059837:android:aa84b91f1d15a92ea74114',
    messagingSenderId: '851203059837',
    projectId: 'petlover-c9863',
    storageBucket: 'petlover-c9863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLvww0kT_Fsr4014EwqQ9AzKqJgPoHyE',
    appId: '1:851203059837:ios:96c07cd43d6a2525a74114',
    messagingSenderId: '851203059837',
    projectId: 'petlover-c9863',
    storageBucket: 'petlover-c9863.appspot.com',
    iosBundleId: 'com.example.petlover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPLvww0kT_Fsr4014EwqQ9AzKqJgPoHyE',
    appId: '1:851203059837:ios:5b1781f20ce337e0a74114',
    messagingSenderId: '851203059837',
    projectId: 'petlover-c9863',
    storageBucket: 'petlover-c9863.appspot.com',
    iosBundleId: 'com.example.petlover.RunnerTests',
  );
}
